### ISSUE TITLE
Error: Cannot find module 'esm'

### ISSUE THREAD

**Issue by borekb** [konsalex/gatsby-wordpress-migrate#6]
I get this error immediately after trying to run `wordpress2gatsby`:

> Error: Cannot find module 'esm'

---

Output of `gatsby info`:

```
  System:
    OS: macOS 10.14.2
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 5.6.2 - /usr/local/bin/zsh
  Binaries:
    Node: 10.12.0 - /var/folders/ly/ffw1d5c91v748gt47gtvd0s80000gn/T/yarn--1547946397088-0.22953610156975968/node
    Yarn: 1.13.0 - /var/folders/ly/ffw1d5c91v748gt47gtvd0s80000gn/T/yarn--1547946397088-0.22953610156975968/yarn
    npm: 6.6.0 - ~/.nvs/node/10.12.0/x64/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 71.0.3578.98
    Safari: 12.0.2
  npmPackages:
    gatsby: ^2.0.91 => 2.0.91
```

**Comment by konsalex** [comment]
Hey @borekb thank you for noticing the issue!

Just updated the package. Run `yarn add -D gatsby-wordpress-migrate@1.0.45` and it will work.

I had forgotten a flag from ESM package 🤷🏻‍♂️

**Comment by borekb** [comment]
Thanks, that helped but I'm getting another error right after that:

```
$ wordpress2gatsby borekbcz.wordpress.2019-01-20.xml content
Successfully loaded file.
Currently Parsing Post No: 1
(node:40964) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'map' of undefined
    at data.rss.channel.(anonymous function).item.map (/Users/borekb/.nvs/node/10.12.0/x64/lib/node_modules/gatsby-wordpress-migrate/functions.js:126:37)
    at Array.map (<anonymous>)
    at Object.dataWrangle (/Users/borekb/.nvs/node/10.12.0/x64/lib/node_modules/gatsby-wordpress-migrate/functions.js:82:28)
    at parser.parseString (/Users/borekb/.nvs/node/10.12.0/x64/lib/node_modules/gatsby-wordpress-migrate/cli.js:47:30)
    at Parser.<anonymous> (/Users/borekb/.nvs/node/10.12.0/x64/lib/node_modules/gatsby-wordpress-migrate/node_modules/xml2js/lib/parser.js:303:18)
    at Parser.emit (events.js:182:13)
    at SAXParser.onclosetag (/Users/borekb/.nvs/node/10.12.0/x64/lib/node_modules/gatsby-wordpress-migrate/node_modules/xml2js/lib/parser.js:261:26)
    at emit (/Users/borekb/.nvs/node/10.12.0/x64/lib/node_modules/gatsby-wordpress-migrate/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/Users/borekb/.nvs/node/10.12.0/x64/lib/node_modules/gatsby-wordpress-migrate/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/Users/borekb/.nvs/node/10.12.0/x64/lib/node_modules/gatsby-wordpress-migrate/node_modules/sax/lib/sax.js:889:7)
(node:40964) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:40964) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by konsalex** [comment]
Hey again @borekb 😅

Updated the package again. Run yarn add -D gatsby-wordpress-migrate@1.0.5 and it will work.

That happened because your post didn't include any categories but know we are good to go! 👍 

Thanks for noticing once again.
