### ISSUE TITLE
Doesn't work on Windows?

### ISSUE THREAD

**Issue by Svish** [konsalex/gatsby-wordpress-migrate#7]
On the same folder as my exported xml file, I ran the following:

```cmd
Y:\projects> mkdir blog && cd blog
Y:\projects\blog> npm init -y
Y:\projects\blog> npm install gatsby-wordpress-migrate
Y:\projects\blog> wordpress2gatsby geekality.WordPress.2019-07-26.xml out
```

Which gave me an empty `out` directory (so that actually got created) and the following error message:

```
Y:\projects\blog>npx wordpress2gatsby geekality.WordPress.2019-07-26.xml out
Successfully loaded file.
Currently Parsing Post No: 1
(node:22896) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, mkdir 'Y:\projects\blog/out/"
                                BCrypt          "'
    at Object.mkdirSync (fs.js:773:3)
    at writing (Y:\projects\blog\node_modules\gatsby-wordpress-migrate\writing.js:40:8)
    at data.rss.channel.(anonymous function).item.map (Y:\projects\blog\node_modules\gatsby-wordpress-migrate\functions.js:146:12)
    at Array.map (<anonymous>)
    at Object.dataWrangle (Y:\projects\blog\node_modules\gatsby-wordpress-migrate\functions.js:82:28)
    at parser.parseString (Y:\projects\blog\node_modules\gatsby-wordpress-migrate\cli.js:47:30)
    at Parser.<anonymous> (Y:\projects\blog\node_modules\xml2js\lib\parser.js:303:18)
    at Parser.emit (events.js:193:13)
    at SAXParser.onclosetag (Y:\projects\blog\node_modules\xml2js\lib\parser.js:261:26)
    at emit (Y:\projects\blog\node_modules\sax\lib\sax.js:624:35)
(node:22896) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:22896) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Looking at `no such file or directory, mkdir 'Y:\projects\blog/out/"`, are your code missing some path slash normalization or something like that? 🤔

**Comment by konsalex** [comment]
As I see it you are right @Svish !

Currently I do not have access on a Windows machine 🙃If you could fix this issue and make a pull request that could be great!
